export const _PopularTourCards = [
	{
		id: 1,
		image: 'tseysky-glacier.png',
		title: 'Поход к подножью Цейского ледника',
		date: '13 октября',
		length: '4 км',
		difficulty: 'Выше средней сложности',
		rating: 4,
		reviewCount: 124,
		price: 3500,
	},
	{
		id: 2,
		image: 'tsei-repeater.png',
		title: 'Поход в Цей через хвойный лес к ретранслятору',
		date: '3 ноября',
		length: '8 км',
		difficulty: 'Средняя сложность',
		rating: 5,
		reviewCount: 89,
		price: 2800,
	},
	{
		id: 3,
		image: 'coniferous-forest.png',
		title: 'Поход по хвойному лесу осеннего Цейского ущелья',
		date: '4 ноября',
		length: '5 км',
		difficulty: 'Легкая сложность',
		rating: 4.7,
		reviewCount: 156,
		price: 3200,
	},
	{
		id: 4,
		image: 'tseyskoye-gorge.jpg',
		title: 'Цейское ущелье',
		date: '12 декабря',
		length: '6 км',
		difficulty: 'Средняя сложность',
		rating: 4.8,
		reviewCount: 124,
		price: 3500,
	},
];