export const _RecommendedPlacesSliders = [
	{
		id: 1,
		image: 'tseyskoye-gorge.jpg',
		title: 'Прогулка по Цейскому ущелью',
		date: '15 ноября',
		length: '3 км',
		difficulty: 'Легкая сложность',
		rating: 4.5,
		reviewCount: 98,
		price: 2500,
	},
	{
		id: 2,
		image: 'coniferous-forest.png',
		title: 'Тропа через хвойный лес',
		date: '20 декабря',
		length: '7 км',
		difficulty: 'Средняя сложность',
		rating: 4.3,
		reviewCount: 145,
		price: 3100,
	},
	{
		id: 3,
		image: 'tsei-repeater.png',
		title: 'Восхождение к ретранслятору',
		date: '5 ноября',
		length: '6 км',
		difficulty: 'Выше средней сложности',
		rating: 4.9,
		reviewCount: 167,
		price: 3800,
	},
	{
		id: 4,
		image: 'tseysky-glacier.png',
		title: 'Экскурсия к леднику',
		date: '25 октября',
		length: '5 км',
		difficulty: 'Средняя сложность',
		rating: 4.6,
		reviewCount: 134,
		price: 3300,
	},
	{
		id: 5,
		image: 'coniferous-forest.png',
		title: 'Панорамный маршрут по лесу',
		date: '8 декабря',
		length: '4.5 км',
		difficulty: 'Легкая сложность',
		rating: 4.4,
		reviewCount: 112,
		price: 2900,
	},
	{
		id: 6,
		image: 'tseyskoye-gorge.jpg',
		title: 'Вечерняя прогулка по ущелью',
		date: '17 ноября',
		length: '3.5 км',
		difficulty: 'Средняя сложность',
		rating: 4.8,
		reviewCount: 178,
		price: 3400,
	},
];
